# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/Second/workspace/Research/bus_test/bus_test.srcs/sources_1/bd/design_1/ip/design_1_top_0_0/design_1_top_0_0.xci
# IP: The module: 'design_1_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /media/Second/workspace/Research/bus_test/bus_test.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: /media/Second/workspace/Research/bus_test/bus_test.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: /media/Second/workspace/Research/bus_test/bus_test.srcs/sources_1/bd/design_1/ip/design_1_top_0_0/design_1_top_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /media/Second/workspace/Research/bus_test/bus_test.srcs/sources_1/bd/design_1/ip/design_1_top_0_0/design_1_top_0_0.xci
# IP: The module: 'design_1_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /media/Second/workspace/Research/bus_test/bus_test.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# XDC: /media/Second/workspace/Research/bus_test/bus_test.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: /media/Second/workspace/Research/bus_test/bus_test.srcs/sources_1/bd/design_1/ip/design_1_top_0_0/design_1_top_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
